In [2]:
import pandas as pd

In [8]:
train = pd.read_csv('..\\0.data\\trainV1.csv')
test = pd.read_csv('..\\0.data\\testV1.csv')

print(train.shape)
print(test.shape)

(889, 12)
(417, 11)

In [9]:
train.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,0,1,0,0,1
1,2,1,1,38.0,1,0,71.2833,1,0,1,0,0
2,3,1,3,26.0,0,0,7.9250,1,0,0,0,1
3,4,1,1,35.0,1,0,53.1000,1,0,0,0,1
4,5,0,3,35.0,0,0,8.0500,0,1,0,0,1

In [10]:
test.head()

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,3,34.5,0,0,7.8292,0,1,0,1,0
1,893,3,47.0,1,0,7.0000,1,0,0,0,1
2,894,2,62.0,0,0,9.6875,0,1,0,1,0
3,895,3,27.0,0,0,8.6625,0,1,0,0,1
4,896,3,22.0,1,1,12.2875,1,0,0,0,1

### Training Models

In [11]:
trainY = train.loc[:, ['Survived']]
trainX = train.iloc[:, 2:]

testX = test.iloc[:, 1:]

In [12]:
print(train.shape)
print(test.shape)

print(trainY.shape)
print(testX.shape)

(889, 12)
(417, 11)
(889, 1)
(417, 10)

In [14]:
trainX

,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,3,22.0,1,0,7.2500,0,1,0,0,1
1,1,38.0,1,0,71.2833,1,0,1,0,0
2,3,26.0,0,0,7.9250,1,0,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,0,1
4,3,35.0,0,0,8.0500,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...
884,2,27.0,0,0,13.0000,0,1,0,0,1
885,1,19.0,0,0,30.0000,1,0,0,0,1
886,3,-1.0,1,2,23.4500,1,0,0,0,1
887,1,26.0,0,0,30.0000,0,1,1,0,0
888,3,32.0,0,0,7.7500,0,1,0,1,0

## Linear Regression

In [15]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from math import sqrt

In [16]:
#Create linear regression object
linear = linear_model.LinearRegression()

#Train the model using the training sets and
#check score
linear.fit(trainX, trainY)
train_r2Score = linear.score(trainX, trainY)

#Predict Output
y_predicted = linear.predict(testX)

print('Intercept: ', linear.intercept_)
print('\nTraining R2 Score: ', train_r2Score)

Intercept:  [0.90440665]

Training R2 Score:  0.38242293000055627

In [17]:
y_predicted

array([[ 8.79173042e-02],
       [ 5.15336036e-01],
       [ 1.76684243e-01],
       [ 8.67591750e-02],
       [ 5.71477290e-01],
       [ 1.19141796e-01],
       [ 6.14904487e-01],
       [ 2.07423615e-01],
       [ 6.85088205e-01],
       [ 3.22128079e-02],
       [ 1.55855997e-01],
       [ 3.57933882e-01],
       [ 9.12055509e-01],
       [ 1.22313447e-01],
       [ 8.45679542e-01],
       [ 7.95981785e-01],
       [ 2.44431697e-01],
       [ 1.61749009e-01],
       [ 5.65175052e-01],
       [ 6.18214689e-01],
       [ 3.69976401e-01],
       [ 1.22019458e-01],
       [ 9.92116942e-01],
       [ 4.84569978e-01],
       [ 9.47403800e-01],
       [-5.53609333e-03],
       [ 9.98198066e-01],
       [ 1.58033890e-01],
       [ 3.71797022e-01],
       [ 1.46490868e-01],
       [ 1.54511141e-01],
       [ 1.83465459e-01],
       [ 5.39441972e-01],
       [ 6.24596507e-01],
       [ 4.31352594e-01],
       [ 1.67942254e-01],
       [ 6.71814270e-01],
       [ 6.17527228e-01],
       [ 9.19880015e-02],
       [ 1.71833646e-01],
       [ 1.11687459e-01],
       [ 4.74521749e-01],
       [ 5.18176185e-02],
       [ 7.52929020e-01],
       [ 8.47798875e-01],
       [ 9.14702073e-02],
       [ 4.22228982e-01],
       [ 1.75815741e-01],
       [ 9.16302778e-01],
       [ 5.67724032e-01],
       [ 3.86350825e-01],
       [ 3.05722092e-01],
       [ 6.98969877e-01],
       [ 8.69559454e-01],
       [ 3.75250442e-01],
       [-9.13923155e-04],
       [ 6.66931501e-02],
       [ 9.13797988e-02],
       [ 1.21303953e-01],
       [ 1.03692109e+00],
       [ 1.11274574e-01],
       [ 2.32232329e-01],
       [ 1.08749895e-01],
       [ 6.34749948e-01],
       [ 4.88448779e-01],
       [ 8.32338204e-01],
       [ 6.44707625e-01],
       [ 3.60848770e-01],
       [ 4.56521241e-01],
       [ 8.49770677e-01],
       [ 6.29804675e-01],
       [ 1.01367591e-01],
       [ 5.97470803e-01],
       [ 4.62444609e-01],
       [ 1.02267226e+00],
       [ 5.12956545e-01],
       [ 1.55906692e-01],
       [ 7.76953637e-01],
       [ 2.37021442e-01],
       [ 6.29804675e-01],
       [ 1.56772158e-01],
       [ 3.33036997e-01],
       [ 3.50503644e-01],
       [ 1.55855997e-01],
       [ 3.33054821e-01],
       [ 1.81364832e-01],
       [ 6.22416914e-01],
       [ 6.24756101e-01],
       [ 6.91723319e-01],
       [ 2.64892964e-01],
       [ 5.79523111e-01],
       [ 1.55816283e-01],
       [ 8.77166703e-01],
       [ 1.55906692e-01],
       [ 4.70547492e-01],
       [ 9.14277317e-02],
       [ 7.79664717e-01],
       [ 8.15632243e-02],
       [ 6.19738238e-01],
       [ 7.16973361e-02],
       [ 9.14303605e-01],
       [ 2.11476293e-01],
       [ 1.75815741e-01],
       [ 8.89441478e-02],
       [ 6.45700032e-01],
       [ 8.88398398e-02],
       [ 1.21350610e-01],
       [ 1.75815741e-01],
       [ 1.56124494e-01],
       [ 2.65504018e-01],
       [ 2.71051761e-01],
       [ 6.91732919e-01],
       [ 9.61077950e-01],
       [ 6.43273345e-01],
       [ 8.58851558e-01],
       [ 1.34306663e-01],
       [ 2.15978518e-01],
       [ 6.24939596e-01],
       [ 4.59491901e-01],
       [ 7.22430380e-01],
       [ 7.98414529e-01],
       [ 1.38566498e-01],
       [ 9.34876443e-01],
       [ 8.38180583e-02],
       [ 1.75815741e-01],
       [ 6.22363651e-01],
       [ 9.88579690e-02],
       [ 6.22320587e-01],
       [ 2.07300493e-01],
       [ 9.39880478e-02],
       [ 7.41740818e-02],
       [ 4.02020506e-01],
       [ 6.47477359e-01],
       [ 1.78729276e-01],
       [ 4.68791841e-02],
       [ 9.39236770e-02],
       [ 1.48126907e-01],
       [ 2.46928425e-01],
       [ 6.12372372e-01],
       [-1.52110617e-02],
       [ 4.56064715e-01],
       [ 9.47314747e-01],
       [ 3.99298527e-01],
       [ 2.46248790e-01],
       [ 3.68021682e-01],
       [-3.18257547e-02],
       [ 4.82843441e-01],
       [ 9.89415393e-02],
       [ 4.74521749e-01],
       [ 1.96530358e-01],
       [ 1.00268412e+00],
       [ 2.16457946e-01],
       [ 5.66502136e-01],
       [-3.51237201e-02],
       [ 9.38236687e-02],
       [ 9.80310156e-01],
       [ 6.12308001e-01],
       [ 3.68021682e-01],
       [ 5.91792878e-01],
       [ 6.91717829e-01],
       [ 1.54295412e-01],
       [ 7.63000382e-01],
       [ 1.55561495e-01],
       [ 2.09777238e-01],
       [ 5.64771590e-01],
       [ 4.21635535e-01],
       [ 2.79732006e-02],
       [ 1.05141619e+00],
       [ 6.15149110e-01],
       [ 1.55742312e-01],
       [ 1.46888534e-01],
       [ 6.11387869e-02],
       [ 2.16238796e-01],
       [-1.27952247e-02],
       [ 7.83596522e-01],
       [ 7.85504485e-01],
       [ 3.71151823e-01],
       [ 7.24069163e-01],
       [ 8.93621849e-01],
       [ 2.37021442e-01],
       [ 4.14852862e-01],
       [ 9.14850446e-01],
       [ 1.75815741e-01],
       [ 1.00956342e+00],
       [ 2.13240259e-01],
       [ 7.70334099e-01],
       [ 3.68267838e-02],
       [ 3.79007565e-01],
       [ 2.12253984e-01],
       [ 1.94139073e-01],
       [ 4.74340932e-01],
       [ 8.23029194e-02],
       [ 1.80036307e-01],
       [ 2.82889236e-01],
       [ 7.16329652e-02],
       [ 5.38244529e-01],
       [ 6.24665692e-01],
       [ 2.53536766e-01],
       [ 6.71834817e-01],
       [ 6.94271195e-01],
       [ 1.39668837e-01],
       [ 4.45062840e-01],
       [ 7.66926343e-01],
       [ 2.48583275e-01],
       [ 5.34857963e-01],
       [ 6.02560472e-01],
       [ 2.51060021e-01],
       [ 9.67206831e-01],
       [ 9.14606076e-02],
       [ 7.89328568e-02],
       [ 1.55577933e-01],
       [ 2.89109008e-01],
       [ 6.45651262e-01],
       [ 4.11102412e-01],
       [ 3.73265375e-01],
       [ 6.91765795e-01],
       [ 3.31578304e-01],
       [ 9.40756132e-01],
       [ 1.55906692e-01],
       [ 7.76563900e-01],
       [ 1.01418285e-01],
       [ 7.71921091e-01],
       [ 1.01334715e-01],
       [ 9.17581508e-01],
       [ 7.19750500e-01],
       [ 9.63812232e-02],
       [ 6.91723319e-01],
       [ 5.54394883e-02],
       [ 2.22160967e-01],
       [ 2.93744800e-01],
       [ 9.35940921e-01],
       [ 6.36580869e-02],
       [ 1.75858216e-01],
       [ 4.13511065e-01],
       [ 1.03830660e-01],
       [ 3.52896507e-01],
       [ 1.64225755e-01],
       [ 7.37885028e-01],
       [ 9.18681054e-01],
       [ 9.12718425e-01],
       [ 7.06335326e-01],
       [ 4.11917901e-01],
       [ 1.55853268e-01],
       [ 1.08688929e-01],
       [ 3.41570877e-01],
       [ 7.75373052e-01],
       [ 1.68946337e-01],
       [ 7.22430380e-01],
       [ 6.97272410e-01],
       [ 7.77521331e-01],
       [ 1.03853936e-01],
       [ 4.64764329e-01],
       [ 9.44072145e-02],
       [ 7.34124084e-02],
       [ 1.55742312e-01],
       [ 1.75815741e-01],
       [ 8.40810648e-02],
       [ 7.80173223e-01],
       [ 1.01327877e-01],
       [ 2.88533730e-02],
       [ 1.01353914e-01],
       [ 7.43661951e-01],
       [ 6.23454694e-01],
       [ 2.97537092e-01],
       [ 1.55855997e-01],
       [ 4.65793218e-01],
       [ 1.55742312e-01],
       [ 6.71814270e-01],
       [ 1.11526632e-01],
       [ 4.34724444e-01],
       [ 1.75815741e-01],
       [ 9.83148653e-01],
       [ 6.57021953e-01],
       [ 2.16237415e-01],
       [ 7.44721092e-01],
       [ 2.41153038e-01],
       [ 1.79278599e-01],
       [ 2.02402265e-01],
       [ 2.56013512e-01],
       [ 6.12573736e-01],
       [ 1.08689586e-01],
       [ 6.91723319e-01],
       [ 6.65249499e-01],
       [ 6.23617614e-01],
       [ 6.40040923e-02],
       [ 1.55643685e-01],
       [ 3.93671185e-01],
       [ 2.16238796e-01],
       [ 1.55906692e-01],
       [ 4.78812043e-01],
       [ 6.14681194e-01],
       [ 2.16238796e-01],
       [ 3.14195595e-01],
       [ 6.47437982e-02],
       [ 8.89838618e-02],
       [ 8.42471603e-01],
       [ 1.46490868e-01],
       [ 4.03972599e-01],
       [ 8.15399482e-02],
       [ 7.40836733e-02],
       [ 3.75075083e-01],
       [ 1.99938114e-01],
       [ 9.41894122e-02],
       [ 6.91723319e-01],
       [ 7.84675913e-01],
       [ 3.86556767e-01],
       [ 1.44285934e-01],
       [ 3.13069408e-01],
       [ 5.22626439e-01],
       [ 1.09049887e-01],
       [ 1.59272263e-01],
       [ 1.55750531e-01],
       [ 5.97606981e-01],
       [ 9.48195544e-01],
       [ 6.47136405e-01],
       [ 3.93664587e-01],
       [ 2.63443749e-01],
       [ 8.64934397e-02],
       [ 1.88418950e-01],
       [ 8.89441478e-02],
       [ 1.51843407e-01],
       [ 2.46928425e-01],
       [ 3.90312393e-01],
       [ 9.52109904e-01],
       [ 9.61360354e-02],
       [ 7.24043974e-01],
       [ 4.36025767e-01],
       [ 2.06522802e-01],
       [ 2.59312153e-01],
       [ 7.01124207e-01],
       [ 4.37089456e-01],
       [ 2.16237415e-01],
       [ 6.40645073e-01],
       [ 8.65071161e-02],
       [ 3.97561814e-01],
       [ 2.32067950e-01],
       [ 1.02137569e-01],
       [ 2.55487197e-01],
       [ 2.16238796e-01],
       [ 2.65920495e-01],
       [ 7.40193025e-02],
       [ 7.12347915e-02],
       [ 1.05709148e+00],
       [ 1.13262241e-01],
       [ 6.29578089e-01],
       [ 2.46928425e-01],
       [ 6.35553290e-01],
       [ 2.52046295e-01],
       [ 7.53082340e-01],
       [ 9.41686304e-01],
       [ 2.48583275e-01],
       [ 2.86632262e-01],
       [ 1.54778060e-01],
       [ 6.20753535e-01],
       [ 3.48026899e-01],
       [ 7.75521777e-01],
       [ 1.55850540e-01],
       [ 1.75815741e-01],
       [ 5.60251596e-01],
       [-1.75289572e-01],
       [ 7.91518081e-01],
       [ 7.53082340e-01],
       [ 8.67591750e-02],
       [ 9.58885028e-01],
       [ 5.87142370e-01],
       [ 1.81366180e-01],
       [ 6.25250205e-01],
       [ 9.40384980e-01],
       [ 3.00382310e-01],
       [ 2.21569774e-01],
       [ 1.00726486e+00],
       [ 3.41955931e-01],
       [ 2.02347001e-01],
       [ 8.27626428e-01],
       [ 1.01463038e+00],
       [ 5.40551998e-01],
       [ 2.58819016e-01],
       [ 3.43533367e-01],
       [-1.53097541e-02],
       [ 1.75815741e-01],
       [ 1.08986081e-01],
       [ 6.73934760e-01],
       [ 5.87676616e-01],
       [ 3.13759465e-01],
       [ 7.32604282e-01],
       [ 9.38976393e-02],
       [ 1.70149307e-01],
       [ 1.21327334e-01],
       [ 2.35881219e-02],
       [ 4.37090213e-01],
       [ 8.58347393e-01],
       [ 1.10211704e-01],
       [ 1.94094868e-01],
       [-3.30647100e-02],
       [ 9.17118878e-01],
       [ 1.13732718e-01],
       [ 9.02214913e-01],
       [ 9.88511308e-02],
       [ 9.65543864e-02],
       [ 9.59122959e-01],
       [ 1.82588299e-01],
       [ 9.97350133e-01],
       [ 4.36696306e-01],
       [ 3.89282553e-01],
       [ 3.22674402e-01],
       [ 2.16287524e-01],
       [ 4.24848554e-01],
       [ 6.91713719e-01],
       [ 6.19024487e-01],
       [ 6.91723319e-01],
       [ 8.99931131e-01],
       [ 5.99898235e-01],
       [ 1.55906692e-01],
       [ 9.79034685e-01],
       [ 5.78122279e-02],
       [ 1.55906692e-01],
       [ 1.76447671e-01]])