In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer

In [2]:
data = pd.read_csv('C:\\Users\\rritesh\\Master\\Projects\\Case Studies\\MASTER\\AirBNB\\Airbnb Datasets\\train.csv')
print(data.shape)
data.head(1)

(74111, 29)

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0

In [3]:
print("ColName\t\t" + 'Unique Count\t' + 'Null Count')
for c in data.columns:
    print(c + ' \t ' + str(data[c].nunique()) + ' \t\t ' + str(data[c].isnull().sum()))

ColName		Unique Count	Null Count
id 	 74111 		 0
log_price 	 767 		 0
property_type 	 35 		 0
room_type 	 3 		 0
amenities 	 67122 		 0
accommodates 	 16 		 0
bathrooms 	 17 		 200
bed_type 	 5 		 0
cancellation_policy 	 5 		 0
cleaning_fee 	 2 		 0
city 	 6 		 0
description 	 73479 		 0
first_review 	 2554 		 15864
host_has_profile_pic 	 2 		 188
host_identity_verified 	 2 		 188
host_response_rate 	 80 		 18299
host_since 	 3087 		 188
instant_bookable 	 2 		 0
last_review 	 1371 		 15827
latitude 	 74111 		 0
longitude 	 74111 		 0
name 	 73359 		 0
neighbourhood 	 619 		 6872
number_of_reviews 	 371 		 0
review_scores_rating 	 54 		 16722
thumbnail_url 	 65883 		 8216
zipcode 	 769 		 966
bedrooms 	 11 		 91
beds 	 18 		 131

In [4]:
data.describe()

,id,log_price,accommodates,bathrooms,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
count,7.411100e+04,74111.000000,74111.000000,73911.000000,74111.000000,74111.000000,74111.000000,57389.000000,74020.000000,73980.000000
mean,1.126662e+07,4.782069,3.155146,1.235263,38.445958,-92.397525,20.900568,94.067365,1.265793,1.710868
std,6.081735e+06,0.717394,2.153589,0.582044,3.080167,21.705322,37.828641,7.836556,0.852143,1.254142
min,3.440000e+02,0.000000,1.000000,0.000000,33.338905,-122.511500,0.000000,20.000000,0.000000,0.000000
25%,6.261964e+06,4.317488,2.000000,1.000000,34.127908,-118.342374,1.000000,92.000000,1.000000,1.000000
50%,1.225415e+07,4.709530,2.000000,1.000000,40.662138,-76.996965,6.000000,96.000000,1.000000,1.000000
75%,1.640226e+07,5.220356,4.000000,1.000000,40.746096,-73.954660,23.000000,100.000000,1.000000,2.000000
max,2.123090e+07,7.600402,16.000000,8.000000,42.390437,-70.985047,605.000000,100.000000,10.000000,18.000000

# Drop Columns

In [5]:
columnsToBeDropped = ['id', 'description', 'first_review', 'host_response_rate', \
                      'host_since', 'last_review', 'latitude', 'longitude',\
                      'name', 'neighbourhood', 'zipcode']
data.drop(columnsToBeDropped, axis=1, inplace=True)
data.shape

(74111, 18)

# Data type conversion

In [6]:
# BEFORE
data.dtypes

log_price                 float64
property_type              object
room_type                  object
amenities                  object
accommodates                int64
bathrooms                 float64
bed_type                   object
cancellation_policy        object
cleaning_fee                 bool
city                       object
host_has_profile_pic       object
host_identity_verified     object
instant_bookable           object
number_of_reviews           int64
review_scores_rating      float64
thumbnail_url              object
bedrooms                  float64
beds                      float64
dtype: object

<bound method NDFrame.describe of        log_price property_type        room_type  \
0       5.010635     Apartment  Entire home/apt
1       5.129899     Apartment  Entire home/apt
2       4.976734     Apartment  Entire home/apt
3       6.620073         House  Entire home/apt
4       4.744932     Apartment  Entire home/apt
5       4.442651     Apartment     Private room
6       4.418841     Apartment  Entire home/apt
7       4.787492   Condominium  Entire home/apt
8       4.787492         House     Private room
9       3.583519         House     Private room
10      4.605170     Apartment     Private room
11      5.010635         House  Entire home/apt
12      4.248495     Apartment     Private room
13      5.298317     Apartment  Entire home/apt
14      4.955827     Apartment  Entire home/apt
15      4.094345     Apartment     Private room
16      4.317488          Loft     Private room
17      4.595120     Townhouse     Private room
18      4.882802     Apartment  Entire home/apt
19      4.595120         House  Entire home/apt
20      4.382027         House     Private room
21      3.688879         House     Private room
22      4.905275     Apartment  Entire home/apt
23      4.007333         House     Private room
24      6.956545     Apartment  Entire home/apt
25      5.003946     Apartment  Entire home/apt
26      4.553877     Apartment  Entire home/apt
27      5.003946     Apartment  Entire home/apt
28      5.192957     Apartment  Entire home/apt
29      4.653960     Apartment     Private room
...          ...           ...              ...
74081   6.907755         Other  Entire home/apt
74082   4.174387         House     Private room
74083   5.010635     Apartment     Private room
74084   5.843544         Other  Entire home/apt
74085   4.653960     Apartment  Entire home/apt
74086   4.174387         House     Private room
74087   4.477337     Apartment  Entire home/apt
74088   4.905275         House  Entire home/apt
74089   4.605170         House     Private room
74090   4.317488         House     Private room
74091   5.010635     Apartment  Entire home/apt
74092   4.700480     Apartment  Entire home/apt
74093   4.948760         House  Entire home/apt
74094   3.688879     Apartment     Private room
74095   4.382027     Apartment  Entire home/apt
74096   3.912023     Apartment     Private room
74097   4.700480     Apartment     Private room
74098   4.553877     Apartment  Entire home/apt
74099   4.276666   Condominium     Private room
74100   4.605170     Apartment     Private room
74101   4.584967     Apartment     Private room
74102   4.110874         Villa      Shared room
74103   5.135798     Apartment  Entire home/apt
74104   4.356709     Apartment  Entire home/apt
74105   4.248495         House     Private room
74106   4.605170     Apartment     Private room
74107   5.043425     Apartment  Entire home/apt
74108   5.220356     Apartment  Entire home/apt
74109   5.273000     Apartment  Entire home/apt
74110   4.852030          Boat  Entire home/apt

                                               amenities  accommodates  \
0      {"Wireless Internet","Air conditioning",Kitche...             3
1      {"Wireless Internet","Air conditioning",Kitche...             7
2      {TV,"Cable TV","Wireless Internet","Air condit...             5
3      {TV,"Cable TV",Internet,"Wireless Internet",Ki...             4
4      {TV,Internet,"Wireless Internet","Air conditio...             2
5      {TV,"Wireless Internet",Heating,"Smoke detecto...             2
6      {TV,Internet,"Wireless Internet","Air conditio...             3
7      {TV,"Cable TV","Wireless Internet","Wheelchair...             2
8      {TV,"Cable TV","Wireless Internet","Pets live ...             2
9      {"Wireless Internet","Air conditioning",Kitche...             2
10     {Internet,"Wireless Internet","Air conditionin...             2
11     {TV,"Cable TV",Internet,"Wireless Internet",Ki...             4
12     {TV,Internet,"Wireless Internet",Kitchen,"Free...             2
13     {TV,"Cable TV",Internet,"Wireless Internet","A...             6
14     {Kitchen,Heating,"Smoke detector","Carbon mono...             2
15     {Internet,"Wireless Internet","Air conditionin...             2
16     {TV,"Wireless Internet",Kitchen,"Pets allowed"...             2
17     {Internet,"Wireless Internet","Air conditionin...             2
18     {TV,"Cable TV",Internet,"Wireless Internet","A...             2
19     {TV,"Wireless Internet","Air conditioning",Kit...             8
20     {"Cable TV",Internet,"Wireless Internet","Air ...             2
21     {Internet,"Air conditioning",Kitchen,"Smoking ...             2
22     {TV,"Cable TV",Internet,"Wireless Internet","A...             4
23     {Internet,"Wireless Internet","Air conditionin...             2
24     {TV,"Wireless Internet","Air conditioning",Kit...             4
25     {TV,"Cable TV",Internet,"Wireless Internet","A...             6
26     {TV,"Wireless Internet",Pool,Kitchen,"Elevator...             2
27     {TV,"Cable TV","Wireless Internet","Air condit...             4
28     {TV,Internet,"Wireless Internet","Air conditio...             3
29     {TV,Internet,"Wireless Internet","Air conditio...             3
...                                                  ...           ...
74081  {TV,"Wireless Internet","Air conditioning",Kit...            16
74082  {TV,"Cable TV",Internet,"Wireless Internet","F...             1
74083  {TV,"Wireless Internet",Kitchen,"Smoke detecto...             2
74084  {TV,"Wireless Internet","Air conditioning",Kit...             4
74085  {TV,"Cable TV",Internet,"Wireless Internet","A...             2
74086  {TV,"Wireless Internet",Heating,"Smoke detecto...             2
74087  {TV,"Wireless Internet","Air conditioning",Poo...             4
74088  {TV,Internet,"Wireless Internet","Air conditio...             5
74089  {TV,"Cable TV",Internet,"Air conditioning",Poo...             2
74090  {TV,Internet,"Smoke detector","Wireless Intern...             2
74091  {"Wireless Internet","Air conditioning",Kitche...             2
74092  {TV,"Cable TV",Internet,"Wireless Internet","A...             4
74093  {TV,"Cable TV",Internet,"Wireless Internet","A...             4
74094  {TV,Internet,"Wireless Internet","Air conditio...             2
74095  {TV,"Cable TV",Internet,"Wireless Internet","A...             2
74096  {TV,"Cable TV",Internet,"Wireless Internet","A...             2
74097  {Internet,"Wireless Internet","Air conditionin...             2
74098  {Internet,"Wireless Internet","Air conditionin...             4
74099  {TV,Internet,"Wireless Internet","Air conditio...             2
74100  {Internet,"Wireless Internet","Air conditionin...             2
74101  {TV,Internet,"Wireless Internet",Pool,Kitchen,...             1
74102  {TV,"Wireless Internet","Air conditioning",Kit...            10
74103  {TV,"Cable TV",Internet,"Wireless Internet","A...             2
74104  {TV,"Cable TV",Internet,"Wireless Internet","A...             2
74105  {TV,Internet,"Wireless Internet","Air conditio...             2
74106                                                 {}             1
74107  {TV,"Cable TV",Internet,"Wireless Internet",Ki...             4
74108  {TV,Internet,"Wireless Internet","Air conditio...             5
74109  {TV,"Wireless Internet","Air conditioning",Kit...             2
74110  {TV,Internet,"Wireless Internet",Kitchen,"Free...             4

       bathrooms  bed_type cancellation_policy  cleaning_fee     city  \
0            1.0  Real Bed              strict          True      NYC
1            1.0  Real Bed              strict          True      NYC
2            1.0  Real Bed            moderate          True      NYC
3            1.0  Real Bed            flexible          True       SF
4            1.0  Real Bed            moderate          True       DC
5            1.0  Real Bed              strict          True       SF
6            1.0  Real Bed            moderate          True       LA
7            1.0  Real Bed            moderate          True       LA
8            1.0  Real Bed            moderate          True       SF
9            1.0  Real Bed            moderate          True       LA
10           1.0  Real Bed              strict          True      NYC
11           1.5  Real Bed              strict          True       LA
12           1.0  Real Bed            flexible          True       LA
13           1.5  Real Bed              strict          True       DC
14           1.0  Real Bed              strict          True       LA
15           1.5  Real Bed            moderate          True  Chicago
16           1.0  Real Bed              strict         False  Chicago
17           2.0  Real Bed              strict          True   Boston
18           1.0  Real Bed              strict          True      NYC
19           1.0  Real Bed              strict          True      NYC
20           1.0  Real Bed              strict          True       LA
21           1.5  Real Bed              strict          True      NYC
22           1.0  Real Bed            moderate          True       LA
23           1.0  Real Bed            moderate          True       LA
24           1.0  Real Bed            moderate          True       DC
25           1.0  Real Bed              strict          True      NYC
26           1.0  Real Bed            flexible          True       LA
27           1.0  Real Bed              strict          True      NYC
28           1.0  Real Bed            flexible          True       LA
29           1.0  Real Bed              strict          True      NYC
...          ...       ...                 ...           ...      ...
74081        1.0  Real Bed            moderate         False       LA
74082        1.0  Real Bed            flexible          True       SF
74083        1.0  Real Bed            flexible         False       SF
74084        1.0  Real Bed              strict         False      NYC
74085        1.0  Real Bed            flexible         False       DC
74086        1.0  Real Bed              strict          True      NYC
74087        1.0  Real Bed              strict          True       LA
74088        2.5  Real Bed            flexible         False       DC
74089        1.0  Real Bed              strict          True       LA
74090        1.0  Real Bed            flexible         False      NYC
74091        1.0  Real Bed            moderate         False      NYC
74092        2.0  Real Bed              strict          True  Chicago
74093        1.0  Real Bed              strict          True       DC
74094        1.0  Real Bed              strict          True      NYC
74095        1.0  Real Bed            flexible         False      NYC
74096        1.0  Real Bed            flexible         False      NYC
74097        1.0  Real Bed            flexible          True      NYC
74098        1.0  Real Bed            flexible          True       LA
74099        1.0  Real Bed            moderate          True       LA
74100        1.0  Real Bed              strict          True      NYC
74101        1.0  Real Bed            moderate          True       LA
74102        3.0  Real Bed            flexible         False       LA
74103        1.0  Real Bed            moderate          True       SF
74104        1.0  Real Bed              strict          True  Chicago
74105        1.0  Real Bed            moderate          True       LA
74106        1.0  Real Bed            flexible         False      NYC
74107        2.0  Real Bed            moderate          True       LA
74108        1.0  Real Bed            moderate          True      NYC
74109        1.0  Real Bed              strict          True      NYC
74110        1.0  Real Bed            moderate         False       LA

      host_has_profile_pic host_identity_verified instant_bookable  \
0                        t                      t                f
1                        t                      f                t
2                        t                      t                t
3                        t                      t                f
4                        t                      t                t
5                        t                      t                t
6                        t                      f                t
7                        t                      t                f
8                        t                      f                f
9                        t                      f                t
10                       t                      t                f
11                       t                      t                f
12                       t                      f                f
13                       t                      t                t
14                       t                      t                f
15                       t                      t                f
16                       t                      f                f
17                       t                      t                f
18                       t                      t                f
19                       t                      f                t
20                       t                      t                f
21                       t                      t                f
22                       t                      t                t
23                       t                      t                f
24                       t                      f                f
25                       t                      t                f
26                       t                      t                f
27                       t                      f                f
28                       t                      t                f
29                       t                      f                f
...                    ...                    ...              ...
74081                    t                      f                t
74082                    t                      t                f
74083                    t                      t                f
74084                    t                      t                f
74085                    t                      t                f
74086                    t                      f                f
74087                    t                      t                t
74088                    t                      t                f
74089                    t                      f                f
74090                    t                      t                f
74091                    t                      t                f
74092                    t                      t                t
74093                    t                      t                f
74094                    t                      t                f
74095                    t                      t                f
74096                    t                      f                f
74097                    t                      t                t
74098                    t                      t                f
74099                    t                      t                t
74100                    t                      t                f
74101                    t                      t                f
74102                    t                      f                f
74103                    t                      f                f
74104                    t                      t                f
74105                    t                      t                f
74106                    t                      t                f
74107                    t                      f                f
74108                    t                      t                t
74109                    t                      f                t
74110                    t                      t                f

       number_of_reviews  review_scores_rating  \
0                      2                 100.0
1                      6                  93.0
2                     10                  92.0
3                      0                   NaN
4                      4                  40.0
5                      3                 100.0
6                     15                  97.0
7                      9                  93.0
8                    159                  99.0
9                      2                  90.0
10                    82                  93.0
11                    29                  97.0
12                     0                   NaN
13                    13                  89.0
14                     2                 100.0
15                     0                   NaN
16                    15                  91.0
17                    12                  88.0
18                    26                  86.0
19                     5                  72.0
20                    26                  98.0
21                    57                  89.0
22                    73                  99.0
23                     2                 100.0
24                     0                   NaN
25                    14                 100.0
26                     1                 100.0
27                     4                 100.0
28                     4                  95.0
29                    40                  88.0
...                  ...                   ...
74081                  0                   NaN
74082                 60                  94.0
74083                  0                   NaN
74084                  4                 100.0
74085                  3                  87.0
74086                  4                  95.0
74087                  5                 100.0
74088                  3                  90.0
74089                  0                   NaN
74090                 16                 100.0
74091                  5                 100.0
74092                 15                  96.0
74093                 19                  91.0
74094                  7                  86.0
74095                  0                   NaN
74096                  2                  60.0
74097                 31                  92.0
74098                177                  88.0
74099                 50                  96.0
74100                 32                  93.0
74101                  4                  90.0
74102                  1                  80.0
74103                 24                  98.0
74104                  6                 100.0
74105                 36                  91.0
74106                  0                   NaN
74107                 16                  93.0
74108                 43                  94.0
74109                  0                   NaN
74110                205                  96.0

                                           thumbnail_url  bedrooms  beds
0      https://a0.muscache.com/im/pictures/6d7cbbf7-c...       1.0   1.0
1      https://a0.muscache.com/im/pictures/348a55fe-4...       3.0   3.0
2      https://a0.muscache.com/im/pictures/6fae5362-9...       1.0   3.0
3      https://a0.muscache.com/im/pictures/72208dad-9...       2.0   2.0
4                                                    NaN       0.0   1.0
5      https://a0.muscache.com/im/pictures/82509143-4...       1.0   1.0
6      https://a0.muscache.com/im/pictures/4c920c60-4...       1.0   1.0
7      https://a0.muscache.com/im/pictures/61bd05d5-c...       1.0   1.0
8      https://a0.muscache.com/im/pictures/0ed6c128-7...       1.0   1.0
9      https://a0.muscache.com/im/pictures/8d2f08ce-b...       1.0   1.0
10     https://a0.muscache.com/im/pictures/21726900/1...       1.0   1.0
11                                                   NaN       2.0   2.0
12     https://a0.muscache.com/im/pictures/be827784-a...       1.0   1.0
13                                                   NaN       2.0   3.0

In [8]:
categoryColumns = ["property_type", "room_type", "amenities", "bed_type", "cancellation_policy", "cleaning_fee", "city", \
                   "host_has_profile_pic", "host_identity_verified", "instant_bookable", "thumbnail_url"]
rawData[categoryColumns] = rawData[categoryColumns].apply(lambda x: x.astype('category'))
rawData.dtypes

NameError: name 'rawData' is not defined

# Data Imputation (Missing Values)

In [9]:
data.isnull().sum()

log_price                     0
property_type                 0
room_type                     0
amenities                     0
accommodates                  0
bathrooms                   200
bed_type                      0
cancellation_policy           0
cleaning_fee                  0
city                          0
host_has_profile_pic        188
host_identity_verified      188
instant_bookable              0
number_of_reviews             0
review_scores_rating      16722
thumbnail_url              8216
bedrooms                     91
beds                        131
dtype: int64

### Imputing Bedrooms, Bathrooms, and Beds

In [10]:
# LOGIC - Number of bedrooms = bathrooms and vice versa.
bathroomC = 0
bedroomC = 0
bedsC = 0
for index, row in data.iterrows():
    if (pd.isna(row['bathrooms']) == True) and (pd.isna(row['bedrooms']) == False):
        data.at[index, 'bathrooms'] = data.at[index, 'bedrooms']
        bathroomC = bathroomC + 1
    if (pd.isna(row['bedrooms']) == True) and (pd.isna(row['bathrooms']) == False):
        data.at[index, 'bedrooms'] = data.at[index, 'bathrooms']
        bedroomC = bedroomC + 1
for index, row in data.iterrows():
    if (pd.isna(row['beds']) == True) and (pd.isna(row['bedrooms']) == False):
        data.at[index, 'beds'] = data.at[index, 'bedrooms'] * 2
        bedsC = bedsC + 1

print('{} counts of Bathroom, {} counts of Bedrooms, {} of Beds attr. are imputed' .format(bathroomC, bedroomC, bedsC))

195 counts of Bathroom, 86 counts of Bedrooms, 128 of Beds attr. are imputed

In [11]:
# Clearly the hosts who are not verified are the only ones who do not have a profile picture.
# data['host_has_profile_pic'].value_counts()

# Convert 't/f' to 1/0 for Imputer to work
for index, row in data.iterrows():
    if row['host_identity_verified'] == 't':
        data.at[index, 'host_identity_verified'] = 1
        data.at[index, 'host_has_profile_pic'] = 1
    elif row['host_identity_verified'] == 'f':
        data.at[index, 'host_identity_verified'] = 0
        data.at[index, 'host_has_profile_pic'] = 0

In [ ]:
categoryCols = ['host_has_profile_pic', 'host_identity_verified']

# categoryData = data.loc[:,categoryCols]
# categoryData.head()
imp = Imputer(missing_values=np.NaN, strategy='most_frequent')
data = pd.DataFrame(imp.fit_transform(data), columns=categoryCols)

# # numericalData = rawData.loc[:,['review_scores_rating']]
# # imp = Imputer(missing_values=np.nan, strategy='mean')
# # numericalData = pd.DataFrame(imp.fit_transform(numericalData), columns=['review_scores_rating'])
# # rawData.isnull().sum()

In [158]:
dat

In [1]:
rawData.isnull().sum()

NameError: name 'rawData' is not defined

# Imputing Neighbourhoods

# from geopy.geocoders import Nominatim
# geolocator = Nominatim(user_agent="temp")

# for index, row in rawData.iterrows():
# #     if pd.isna(row['neighbourhood']) == True and index <= 100:
#     if pd.isna(row['neighbourhood']) == True:
#         latlongtext = str(row['latitude']) + ',' + str(row['longitude'])
#         location = geolocator.reverse(latlongtext)
#         locDict = location.raw['address']
        
#         if 'neighbourhood' in locDict.keys():
#             rawData.at[index, 'neighbourhood'] = locDict['neighbourhood']
# #         elif 'suburb' in locDict.keys():
# #             rawData.at[index, 'neighbourhood'] = locDict['suburb']
# #         elif 'hamlet' in locDict.keys():
# #             rawData.at[index, 'neighbourhood'] = locDict['hamlet']
#         else:
#             continue

# #       print('{} = {} ||| {}' .format(index, locDict, row['city']))